### ISSUE TITLE
RP-1 compat was removed when RO_Basic_Compatability.cfg was removed

### ISSUE THREAD

**Issue by StonesmileGit** [AlphaMensae/Modular-Launch-Pads#12]
When the Realism Overhaul compatibilty patch was moved into RO, the patch for RP-1 was removed without any replacement.

Some part of [the original file](https://github.com/AlphaMensae/Modular-Launch-Pads/blob/bbab246a2c4bf69e9972c9ca9cf72c284a4e5c5f/Extras/RO_Basic_Patch/RO_Basic_Compatibility.cfg) should probably be re-introduced to allow for compatability.

**Comment by kyleander** [comment]
RP-1 Compat was added with this [patch in RP-0](https://github.com/KSP-RO/RP-0/commit/be9a862ecafa7611bdb279b653234343ce71aa99#diff-e4a6a56c1264c82568d476de090410e87639c117b26fd18d88fb3d456c7eed02) now.
