### ISSUE TITLE
Screen goes black when detaching from soyuz base

### ISSUE THREAD

**Issue by Khitiara** [AlphaMensae/Modular-Launch-Pads#16]
Instruments not affected, only world view, and is resolved usually with some distance from the pad.

**Comment by Mariouzs** [comment]
> Instruments not affected, only world view, and is resolved usually with some distance from the pad.

Same issue here, at the moment of detaching from Soyuz platform, the camera goes to a blank map view, pressing the map key twice return to the world view. What is happening?

**Comment by Mariouzs** [comment]
> > Instruments not affected, only world view, and is resolved usually with some distance from the pad.
> 
> Same issue here, at the moment of detaching from Soyuz platform, the camera goes to a blank map view, pressing the map key twice return to the world view. What is happening?

Found the culprit: MOARdV's Avionics Systems

**Comment by Khitiara** [comment]
> > > Instruments not affected, only world view, and is resolved usually with some distance from the pad.
> >
> > Same issue here, at the moment of detaching from Soyuz platform, the camera goes to a blank map view, pressing the map key twice return to the world view. What is happening?
>
> Found the culprit: MOARdV's Avionics Systems

Well thats a weird incompatibility but thanks!
